
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
 * Detected change in '/Users/a/Desktop/data/ted/verify_speakers.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 18:55:48] "[35m[1mGET /talk_detail/3525 HTTP/1.0[0m" 500 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 18:56:18] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 18:56:36] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 18:56:42] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 18:56:45] "[35m[1mPOST /update_chinese_content HTTP/1.0[0m" 500 -
127.0.0.1 - - [08/May/2025 18:56:49] "[35m[1mPOST /update_chinese_content HTTP/1.0[0m" 500 -
127.0.0.1 - - [08/May/2025 18:57:13] "[35m[1mPOST /update_chinese_content HTTP/1.0[0m" 500 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 18:59:35] "[31m[1mPOST /update_chinese_content HTTP/1.0[0m" 415 -
127.0.0.1 - - [08/May/2025 18:59:39] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:00:03] "[31m[1mPOST /update_chinese_content HTTP/1.0[0m" 415 -
127.0.0.1 - - [08/May/2025 19:00:12] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:00:17] "[31m[1mPOST /update_chinese_content HTTP/1.0[0m" 415 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 19:02:53] "[35m[1mPOST /update_chinese_content HTTP/1.0[0m" 500 -
127.0.0.1 - - [08/May/2025 19:02:58] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:03:15] "[35m[1mPOST /update_chinese_content HTTP/1.0[0m" 500 -
127.0.0.1 - - [08/May/2025 19:03:24] "[35m[1mPOST /update_chinese_content HTTP/1.0[0m" 500 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 19:06:51] "[31m[1mPOST /update_chinese_content HTTP/1.0[0m" 400 -
127.0.0.1 - - [08/May/2025 19:06:53] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:07:08] "[31m[1mPOST /update_chinese_content HTTP/1.0[0m" 400 -
127.0.0.1 - - [08/May/2025 19:13:03] "GET /talk_detail/3524 HTTP/1.0" 200 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 19:16:37] "GET /talk_detail/3524 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:16:59] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:17:03] "GET /talk_detail/3524 HTTP/1.0" 200 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 19:18:56] "GET /talk_detail/3524 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:19:11] "[31m[1mPOST /update_chinese_content HTTP/1.0[0m" 400 -
127.0.0.1 - - [08/May/2025 19:19:13] "[31m[1mPOST /update_chinese_content HTTP/1.0[0m" 400 -
127.0.0.1 - - [08/May/2025 19:19:45] "[31m[1mPOST /update_chinese_content HTTP/1.0[0m" 400 -
127.0.0.1 - - [08/May/2025 19:19:48] "GET /talk_detail/3524 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:19:52] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:25:05] "GET /talk_detail/3524 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:25:13] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:25:17] "GET /talk_detail/3524 HTTP/1.0" 200 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 19:25:45] "GET /talk_detail/3524 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:25:53] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:26:58] "GET /talk_detail/3524 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:27:12] "GET /?search_term=&english_name=ZubaidaBai&chinese_name=&year= HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:27:14] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:28:38] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:28:43] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:29:38] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:29:50] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:29:53] "GET /talk_detail/3520 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:32:58] "GET /talk_detail/3520 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:33:15] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:38:03] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:38:10] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:38:24] "GET /talk_detail/3520 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:38:58] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:40:35] "GET /talk_detail/3517 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:41:08] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:44:31] "GET /talk_detail/3517 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:44:52] "GET /talk_detail/3520 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:45:07] "GET /talk_detail/3517 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:46:18] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:49:57] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:50:09] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:50:19] "GET /talk_detail/3522 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:50:47] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:52:19] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:53:02] "GET /talk_detail/3450 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:53:51] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:55:32] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:56:20] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:59:30] "GET /talk_detail/3450 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:59:35] "[33mGET /speakers HTTP/1.0[0m" 404 -
127.0.0.1 - - [08/May/2025 19:59:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 19:59:46] "[33mGET /speakers HTTP/1.0[0m" 404 -
127.0.0.1 - - [08/May/2025 20:00:06] "[33mGET /speakers HTTP/1.0[0m" 404 -
127.0.0.1 - - [08/May/2025 20:00:23] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:00:26] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:00:28] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:00:30] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:03:00] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:03:47] "GET /talk_detail/3517 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:04:30] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:04:46] "GET /talk_detail/3502 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:05:15] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:09:49] "GET /talk_detail/3500 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:10:23] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:10:24] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:18:48] "GET /talk_detail/3502 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:18:58] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:19:10] "GET /talk_detail/3524 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:19:25] "GET /talk_detail/3523 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:19:47] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:20:27] "GET /talk_detail/3521 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:20:34] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:21:33] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:21:58] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:22:49] "[35m[1mGET / HTTP/1.0[0m" 500 -
Traceback (most recent call last):
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 379, in show_speakers
    return render_template('speakers.html',
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/a/Desktop/data/ted/templates/speakers.html", line 176, in top-level template code
    {% if talk.chinese_content %}
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'talk' is undefined
127.0.0.1 - - [08/May/2025 20:22:49] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.0[0m" 304 -
127.0.0.1 - - [08/May/2025 20:22:49] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.0[0m" 304 -
127.0.0.1 - - [08/May/2025 20:22:49] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.0[0m" 304 -
127.0.0.1 - - [08/May/2025 20:28:47] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:28:59] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:29:04] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:29:47] "GET /talk_detail/3525 HTTP/1.0" 200 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 20:33:03] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:33:13] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:33:27] "GET /talk_detail/3504 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:33:43] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:34:23] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:37:16] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:37:27] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:37:38] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:37:50] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:39:18] "GET / HTTP/1.0" 200 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 20:40:44] "GET / HTTP/1.0" 200 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [08/May/2025 20:41:41] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:50:14] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:50:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:51:11] "GET /talk_detail/3524 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:51:37] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:51:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:52:02] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:52:22] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:52:51] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:56:56] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:57:06] "GET /talk_detail/3525 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:57:37] "GET /talk_detail/3495 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:58:01] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:58:01] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:58:38] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:59:13] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:59:23] "GET /page/2?sort_type=english_name_desc HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 20:59:33] "GET /talk_detail/3337 HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 21:00:00] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 21:00:13] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 21:05:18] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [08/May/2025 21:05:39] "GET /talk_detail/3467 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 19:07:32] "GET / HTTP/1.0" 200 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web copy.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [09/May/2025 19:10:29] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:37:24] "GET /page/2?sort_type=english_name_asc HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:37:28] "GET /page/2?sort_type=english_name_desc HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:37:31] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:37:33] "GET /talk_detail/3523 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:37:38] "GET /talk_detail/3518 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:38:25] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:38:52] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:39:20] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:39:25] "GET /talk_detail/3516 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:39:56] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:40:25] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:40:52] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:41:00] "GET /talk_detail/3500 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:43:06] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:43:14] "GET /talk_detail/3506 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:43:35] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:43:35] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:44:42] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:44:51] "GET /talk_detail/3505 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:45:11] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:46:23] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:46:44] "GET /talk_detail/3500 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:46:50] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:46:57] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:47:06] "GET /talk_detail/3470 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:47:31] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:49:05] "GET /talk_detail/3467 HTTP/1.0" 200 -
127.0.0.1 - - [09/May/2025 20:49:24] "POST /update_chinese_content HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 20:12:07] "GET / HTTP/1.0" 200 -
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/a/Desktop/data/ted/speakers_web.py", line 21, in <module>
    raise Exception("无法连接到Elasticsearch，请检查服务是否运行")
Exception: 无法连接到Elasticsearch，请检查服务是否运行
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5050
 * Running on http://192.168.3.59:5050
[33mPress CTRL+C to quit[0m
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [10/May/2025 21:02:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:02:35] "[33mGET /favicon.ico HTTP/1.0[0m" 404 -
127.0.0.1 - - [10/May/2025 21:06:46] "GET / HTTP/1.0" 200 -
 * Detected change in '/Users/a/Desktop/data/ted/speakers_web copy.py', reloading
 * Restarting with stat
/Users/a/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 239-020-829
127.0.0.1 - - [10/May/2025 21:29:13] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:29:50] "GET /?search_term=&english_name=&chinese_name=&year= HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:29:58] "GET /?search_term=&english_name=&chinese_name=&year= HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:44:17] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:44:21] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:45:05] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:48:54] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:50:01] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:52:20] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:52:28] "GET /?search_term=&english_name=&chinese_name=&year= HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:58:05] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:58:12] "GET /?search_term=&english_name=Bill&chinese_name=&year=&bio= HTTP/1.0" 200 -
127.0.0.1 - - [10/May/2025 21:58:23] "GET /?search_term=地方全球化_全球地方化&english_name=&chinese_name=&year=&bio= HTTP/1.0" 200 -
